<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'code'=>'required|min:3|max:255|unique:categories,code',
            'name'=>'required|min:3|max:255',
            'description'=>'required|min:5'
        ];
    }

    public function messages()
    {
        return [
            'required' => 'Поле :attribute обязательно для заполнения',
            'min' => 'Поле :attribute должно содержать как минимум :min символов',
            'code.min' => 'Поле "Код" должно содержать не менее :min символов'
        ];

        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
